branches:
  only:
    - master
cache:
  bundler: true
  directories:
    - $HOME/perl5
    - $HOME/.cpanm
    - $HOME/.cpan
sudo: false
language: erlang
otp_release:
  - R16B03-1
addons:
  postgresql: "9.3"
  apt:
    packages:
      - cpanminus
      - perl
      - libdbd-pg-perl
      - build-essential
env:
  global:
    - PERL5LIB=~/perl5/lib/perl5/x86_64-linux-gnu-thread-multi:~/perl5/lib/perl5:/etc/perl:/usr/local/lib/perl/5.14.2:/usr/local/share/perl/5.14.2:/usr/lib/perl5:/usr/share/perl5:/usr/lib/perl/5.14:/usr/share/perl/5.14:/usr/local/lib/site_perl

install:
  - ./rebar get-deps -C rebar.config.lock
  - cpanm --local-lib=$HOME/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm --notest --quiet App::Sqitch
script:
  - make
  - PATH=~/perl5/bin:$PATH ./rebar skip_deps=true ct
