branches:
  only:
    - master
language: erlang
otp_release:
  - R16B03-1
install:
  - ./rebar get-deps -C rebar.config.lock
script:
  - make
  - ./rebar skip_deps=true ct
  - ./rebar skip_deps=true eunit