description: Environments, representing a logical grouping of nodes with common properties.
type: list_endpoint

/{environment}:
  description: An environment, representing a logical grouping of nodes with common properties.
  type: item_endpoint
  uriParameters:
    environment:
      description: Name of the environment.
      type: string

  /cookbook_versions:
    type: list_endpoint

  /cookbooks:
    type: list_endpoint

    /{cookbook}:
      type: item_endpoint
      uriParameters:
        cookbook:
          description: Name of the cookbook.
          type: string

  /nodes:
    type: list_endpoint

  /roles:
    type: list_endpoint

    /{role}:
      type: item_endpoint
      uriParameters:
        role:
          description: Name of the role.
          type: string

  /recipes:
    type: list_endpoint

  /_acl: !include ../acl_endpoint.yaml
