postgres: &postgres
  adapter:  postgresql
  encoding: unicode
  password:
  pool: 16
  template: template0

development:
  <<: *postgres
  database: oc_id_development
  username: oc_id

test:
  <<: *postgres
  database: oc_id_test
  username: postgres

production:
  <<: *postgres
  database: oc_id
  username: oc_id
