---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[opscode-dev-shim]
      - recipe[oc-id]
    data_bags_path: <%= ENV['PLATFORM_COOKBOOKS_PATH'] || '~/oc/opscode-platform-cookbooks' %>/data_bags
    roles_path: <%= ENV['PLATFORM_COOKBOOKS_PATH'] || '~/oc/opscode-platform-cookbooks' %>/roles
    attributes:
